### ISSUE TITLE
Boston.gov page update with photos

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/creative-team-workflow#133]
https://www.boston.gov/departments/parking-clerk/how-do-parking-meters-work

https://www.boston.gov/departments/mayors-office/city-owned-buildings-boston

https://www.boston.gov/departments/public-works/all-about-street-sweeping

https://www.boston.gov/departments/city-clerk

https://www.boston.gov/housing/affirmative-marketing

https://www.boston.gov/health-and-human-services/boston-bounty-bucks

https://www.boston.gov/health-and-human-services/boston-food-policy-council

https://www.boston.gov/transportation/boston-green-links

https://www.boston.gov/civic-engagement/boston-shines

https://www.boston.gov/arts-and-culture/city-hall-galleries

https://www.boston.gov/innovation-and-technology/doit-internships

https://www.boston.gov/transportation/drive-boston

https://www.boston.gov/civic-engagement/city-hall-go-truck

https://www.boston.gov/arts-and-culture/boston-open-studios-coalition

**Comment by sebastianebarb** [comment]
@GuruAmar9 @KristinaVicario

**Comment by KristinaVicario** [comment]
https://photos.app.goo.gl/ht94LBj6bgnYCD5f7
