### ISSUE TITLE
Brand update based on Brand New artical

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/creative-team-workflow#192]
Review commnets made on http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_city_of_boston_by_ideo.php#.WJzM3bHMw9I
and update visuals as needed.

**Comment by carolinestj** [comment]
https://docs.google.com/document/d/15DKBHPQh9RfSQ7ZVKxsEve0aIOGFh4CVUz0Thi1gjJg/edit
